path = "__Obelisks-of-light__"
require("__Obelisks-of-light__.prototypes.entity.beams")
require("__Obelisks-of-light__.prototypes.entity.projectiles")
require("__Obelisks-of-light__.prototypes.categories.ammo-category")
require("__Obelisks-of-light__.prototypes.items")
require("__Obelisks-of-light__.prototypes.recipes")
require("__Obelisks-of-light__.prototypes.obelisks")
require("__Obelisks-of-light__.prototypes.technology")
require("__Obelisks-of-light__.prototypes.sounds")
require("__Obelisks-of-light__.prototypes.custom-input")